# Generated by Django 3.2.3 on 2021-05-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=35)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
    ]
